name: home
description: "This module responsible for displaying bookmarked books"
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_bloc: 9.0.0
  design_system:
    path: ../../libraries/design/design_system
  local_db:
    path: ../../libraries/core/local_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

