name: search
description: "This module responsible for functionality regarding searching books"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.7
  dio: ^5.8.0+1
  flutter_bloc: 9.0.0
  infinite_scroll_pagination: 4.0.0
  get_it: ^8.0.3
  provider: ^6.1.5
  http: ^0.13.6
  design_system:
    path: ../../libraries/design/design_system
  local_db:
    path: ../../libraries/core/local_db
  remote:
    path: ../../libraries/core/remote
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: