name: book_details
description: "Book details module responsible for displaying detail of the book and saving to the db and deleting it from the db"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  provider: ^6.1.5
  cached_network_image: ^3.3.0
  shimmer: ^2.0.0
  local_db:
    path: ../../libraries/core/local_db
  remote:
    path: ../../libraries/core/remote

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  sqflite_common_ffi: ^2.3.0
  bloc_test: 10.0.0
  dio: 5.8.0+1
flutter:

